spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop

# Swagger
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    groups-order: DESC
    operationsSorter: method
    disable-swagger-default-url: true
    display-request-duration: true

  api-docs:
    path: /api-docs

  show-actuator: true

  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  paths-to-match:
      - /api/**